### ISSUE TITLE
Rails 5 / Mongoid issue ?

### ISSUE THREAD

**Issue by Startouf** [rmm5t/strip_attributes#33]
I am getting some 

> `undefined local variable or method 'strip_attributes``

With Rails 5 and Mongoid edge, are there maybe changes in ActiveModel that made it unuseable ?

**Comment by Startouf** [comment]
My bad, forgot to reset the server, really sorry

**Comment by rmm5t** [comment]
No worries. Thanks for the follow-up.

**Comment by JoshSmith** [comment]
If you're getting the `undefined local variable or method 'strip_attributes'` in `rails console` when it appears to work in your regular `rails server`, you need to restart Spring. You can issue a `spring stop` and then simply `rails console` again; the problem should be resolved.
