### ISSUE TITLE
New option: strip individual lines in multiline string

### ISSUE THREAD

**Issue by manuelmeurer** [rmm5t/strip_attributes#35]
I really like the idea (and implementation) of this gem!
Besides stripping individual strings I'd also like to strip individual lines in a multiline string, but preserve newlines.
Would you accept a PR with a new option that does this?

**Comment by rmm5t** [comment]
Hi @manuelmeurer. Thanks for the kudos. 😊 

🤔 You should be able to accomplish what you're looking for with the existing `:regexp` option.  Let me know if something like this works:

```ruby
  strip_attributes regex: /(^\s+)|(\s+$)/
```

**Comment by rmm5t** [comment]
Hmm. That bot shouldn't have closed this issue so soon. It should have waited 7 days. Sorry about that. Please let me know if the suggestion works out for you or not. Cheers 🍻

**Comment by manuelmeurer** [comment]
Fantastic, thank you! Works like a charm! 😃

**Comment by manuelmeurer** [comment]
For other people finding this: I ended up using this regex: `/(^[[:blank:]]+)|([[:blank:]]+$)/`
With `/(^\s+)|(\s+$)/` blank lines are removed as well.

**Comment by rmm5t** [comment]
@manuelmeurer Great catch. Thanks for sharing!

**Comment by rmm5t** [comment]
I just added an example to the README and to the test suite showing how to remove trailing whitespace using strip_attributes. This will ensure that this kind of behavior remains available and might help others with similar desires.

https://github.com/rmm5t/strip_attributes/blob/master/README.md#using-regex

https://github.com/rmm5t/strip_attributes/blob/master/test/strip_attributes_test.rb#L275-L291
