### ISSUE TITLE
Add config for defaults

### ISSUE THREAD

**Issue by sodapopcan** [rmm5t/strip_attributes#38]
Would you be open to a PR adding config options?

```ruby
StripAttributes.configure do |config|
  config.collapse_spaces = true
end
```

Suggestions in the README for setting defaults would also suffice.  For example, I use:

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # Defaults strip_attributes to squish
  def self.squish_attributes(opts = {})
    strip_attributes({ collapse_spaces: true }.merge(opts))
  end
end
```

**Comment by rmm5t** [comment]
Thanks for asking first. If we were to add config options, that's how I'd like to see them; however, I'm a bit apprehensive about giving the built-in ability to change defaults.  The only option that I think is safe to change as a default globally for an application is `allow_empty`.  Everything else has implications. e.g. Even something that sounds benign, like `collapse_spaces`, would break the syntax of a markdown input field.

I think I would be more open to a PR with a README addition/suggestion using your  `squish_attributes` example.

**Comment by sodapopcan** [comment]
My app that sparked my looking into this actually has no `<textareas>`s and is mostly `<input type="texts">`s, though I didn't think through other implications!

Personally, I like to be very intentional with `strip_attributes` and pass the `:only` option every time, so I was just curious if there was a way native to the gem to reduce the added noise of passing `collapse_spaces` every time.  It's no biggie, though, I'm perfectly content with my solution.

Otherwise, I'm not just gunning to just get a PR accepted or anything here, but if you would truly appreciate the added documentation with examples, I'd be happy to write something up, but I'd also be just as happy not to :)  Lemme know!

Thanks for the gem (and for your response), btw!

**Comment by rmm5t** [comment]
It's totally up to you. This is the first anyone has asked for this particular feature, so I'm not sure if the README addition would help others or add noise. 

Btw, you might be interested in the new `:if` and `:unless` options that were recently added. Not sure if that helps you're particular use-cases or not:
https://github.com/rmm5t/strip_attributes/pull/37

**Comment by joshuapinter** [comment]
Just adding in here that I would find this useful as well. I'm essentially doing a find-and-replace on all occurrences to add `collapse_spaces: true` option. That being said, @rmm5t's comment about it breaking markdown was a 💡 comment because I didn't think of that before and we use some markdown for Product Updates. 

So, a +1 for a config feature but also not a big deal to work around it. :)
