### ISSUE TITLE
Add more matchers

### ISSUE THREAD

**Issue by aried3r** [rmm5t/strip_attributes#39]
Hey, I just came across this gem on the search to strip unicode whitespace from attributes, thanks!

The only think I'd love to see are more matchers for options like `allow_empty`, `replace_newlines` etc.

**Comment by rmm5t** [comment]
Hi @aried3r, Thanks for the feature request.

I don't use the advanced features of the matchers often, but I'd be very open to reviewing a pull-request that adds support for more enhanced rspec matchers.
