### ISSUE TITLE
Override doesn't work, multiple executions

### ISSUE THREAD

**Issue by attenzione** [rmm5t/strip_attributes#40]
I have Rails projects with all models are inherited from `ApplicationRecord`. This is a common way to extend ActiveRecord for all models.
I've added `strip_attributes` to `ApplicationRecord` to enable it for all models.
```
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  strip_attributes
end
```
However, on some models, I need to skip stripping for certain columns.
Adding `strip_attributes` to child models results in multiple callbacks (`before_validation`) execution, which one is default from `ApplicationRecord`, so it strips all attributes.
The same behavior will be with STI or Concerns.

I've played a little with gem and solution is to remove previously created callback
```
module ActiveModel::Validations::HelperMethods
  # Strips whitespace from model fields and converts blank values to nil.
  def strip_attributes(options = {})
    StripAttributes.validate_options(options)

    @strip_attributes_options = options

    if _validation_callbacks.select { |cb| cb.kind.eql?(:before) }.collect(&:filter).include?(:strip_attributes_callback)
      skip_callback :validation, :before, :strip_attributes_callback
    end

    before_validation(:strip_attributes_callback, options.slice(:if, :unless))
  end

  def strip_attributes_callback
    StripAttributes.strip(self, self.class.strip_attributes_options)
  end

  def strip_attributes_options
    return @strip_attributes_options unless @strip_attributes_options.nil?
    return superclass.strip_attributes_options if superclass.respond_to?(:strip_attributes_options)
  end
  ...
```
Now, `strip_attributes` in child classes removes previously attached `before_validation` callback and add new.
With options is not quite a good solution, need more time think about saving/passing them to `StripAttributes`

**Comment by rmm5t** [comment]
> I've added strip_attributes to ApplicationRecord to enable it for all models.

Just like you should never add a global validation for all models, you shouldn't add a global `strip_attributes` for all models. 

Just like any other `before_validation` callback, `strip_attributes` is not designed to be "overridden."  It's designed to be explicit. i.e. It should be declared in every single model that intends to use it.

Your workaround of naming the callback and skipping it and redefining it when "overridden" is reasonable, though unnecessarily complicated. You're welcome to do that, but it's not something I would consider adding as a built-in feature for this gem.

Thanks for the effort here and for sharing your work. I'm sure it will help someone else down the orad.
