### ISSUE TITLE
Notice: incorrect FUNDING.yml 

### ISSUE THREAD

**Issue by attenzione** [rmm5t/strip_attributes#55]
Just noticed, that you have errors when clicking on Sponsor button ;)
```
Some errors were encountered when parsing the FUNDING.yml file
```

**Comment by rmm5t** [comment]
Thank you. I fixed a potential syntax error in the `FUNDING.yml` and I also put in the official application request to github to get approval as a sponsor. In the meantime, the external link still works:

- https://www.paypal.me/rmm5t/5
